-- dump-schema.sql — READ-ONLY. Returns the live database's STRUCTURE (no user data) as
-- ONE cell of SQL text. Paste that cell into supabase/schema.sql on GitHub.
--
-- HOW: Supabase dashboard -> SQL Editor -> paste this whole file -> Run ->
--      click the single result cell -> copy -> GitHub: edit supabase/schema.sql, replace all, commit.
-- Do this after any change to the database, so schema.sql always matches reality.
-- (If copying the cell is awkward, use the results' "Export CSV" and give the file to Claude.)

select E'-- REFERENCE ONLY: a description of the live database, not a script to run.\nSET check_function_bodies = false;\nSET search_path = public, extensions;\n\n' || string_agg(ddl, E'\n\n' order by sort_key collate "C") as schema_sql from (

  select '000_header' as sort_key,
         format('-- Schema snapshot generated %s | database %s | %s',
                to_char(now() at time zone 'utc','YYYY-MM-DD"T"HH24:MI:SS"Z"'),
                current_database(), split_part(version(), ' on ', 1)) as ddl

  union all -- extensions
  select '010_' || e.extname,
         format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname)
  from pg_extension e join pg_namespace n on n.oid = e.extnamespace
  where e.extname <> 'plpgsql'

  union all -- enum types
  select '020_' || t.typname,
         format('CREATE TYPE public.%I AS ENUM (%s);', t.typname,
                string_agg(quote_literal(en.enumlabel), ', ' order by en.enumsortorder))
  from pg_type t join pg_enum en on en.enumtypid = t.oid
  where t.typnamespace = 'public'::regnamespace
  group by t.typname

  union all -- tables and their columns
  select '030_' || c.relname,
         format(E'CREATE TABLE public.%I (\n  %s\n);', c.relname,
           string_agg(
             format('%I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
               case when a.attidentity = 'a' then ' GENERATED ALWAYS AS IDENTITY'
                    when a.attidentity = 'd' then ' GENERATED BY DEFAULT AS IDENTITY' else '' end,
               case when a.attgenerated = 's' then ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
                    when d.adbin is not null and a.attidentity = '' then ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
                    else '' end,
               case when a.attnotnull then ' NOT NULL' else '' end),
             E',\n  ' order by a.attnum))
  from pg_class c
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p')
  group by c.relname

  union all -- constraints (primary/unique first, then checks, then foreign keys)
  select '040_' || case k.contype when 'p' then 'a' when 'u' then 'b' when 'c' then 'c' else 'd' end
                || '_' || k.conrelid::regclass::text || '_' || k.conname,
         format('ALTER TABLE ONLY public.%I ADD CONSTRAINT %I %s;', (select relname from pg_class where oid = k.conrelid), k.conname, pg_get_constraintdef(k.oid))
  from pg_constraint k
  where k.connamespace = 'public'::regnamespace and k.contype in ('p', 'u', 'c', 'f', 'x')

  union all -- indexes that are not already created by a constraint
  select '050_' || ic.relname, pg_get_indexdef(x.indexrelid) || ';'
  from pg_index x join pg_class ic on ic.oid = x.indexrelid
  where ic.relnamespace = 'public'::regnamespace and not x.indisprimary
    and not exists (select 1 from pg_constraint k where k.conindid = x.indexrelid)

  union all -- functions (full definition incl. SECURITY DEFINER / search_path)
  select '060_' || p.proname || '_' || p.oid, pg_get_functiondef(p.oid) || ';'
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')

  union all -- who may execute each function (audit-critical for SECURITY DEFINER ones)
  select '061_' || p.proname || '_' || p.oid,
         case when p.proacl is null
              then format('-- public.%s(%s): default privileges (PUBLIC can execute)', p.proname, pg_get_function_identity_arguments(p.oid))
              else format('REVOKE ALL ON FUNCTION public.%I(%s) FROM PUBLIC;', p.proname, pg_get_function_identity_arguments(p.oid))
                   || coalesce((select string_agg(format(E'\nGRANT EXECUTE ON FUNCTION public.%I(%s) TO %s;', p.proname,
                                    pg_get_function_identity_arguments(p.oid),
                                    case when x.grantee = 0 then 'PUBLIC' else x.grantee::regrole::text end), '' order by x.grantee)
                                from aclexplode(p.proacl) x where x.grantee <> p.proowner), '')
         end
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')

  union all -- views (with their options; grants listed further down)
  select '070_' || c.relname,
         format(E'CREATE OR REPLACE VIEW public.%I%s AS\n%s', c.relname,
                case when c.reloptions is not null then ' WITH (' || array_to_string(c.reloptions, ', ') || ')' else '' end,
                pg_get_viewdef(c.oid, true))
  from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind = 'v'

  union all -- row level security switched on
  select '080_' || c.relname,
         format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname)
         || case when c.relforcerowsecurity then format(E'\nALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', c.relname) else '' end
  from pg_class c
  where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p') and c.relrowsecurity

  union all -- tables where RLS is OFF (audit-critical)
  select '081_tables_without_rls',
         '-- Tables with row level security DISABLED: ' ||
         coalesce((select string_agg(c.relname, ', ' order by c.relname) from pg_class c
                   where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p') and not c.relrowsecurity), '(none)')

  union all -- policies on app tables and on storage (file) tables
  select '090_' || p.schemaname || '.' || p.tablename || '.' || p.cmd || '.' || p.policyname,
         format('CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;', p.policyname, p.schemaname, p.tablename,
                p.permissive, p.cmd, array_to_string(p.roles, ', '),
                case when p.qual is not null then E'\n  USING (' || p.qual || ')' else '' end,
                case when p.with_check is not null then E'\n  WITH CHECK (' || p.with_check || ')' else '' end)
  from pg_policies p where p.schemaname in ('public', 'storage')

  union all -- triggers on app tables and on auth.users (new-signup trigger lives there)
  select '100_' || t.tgrelid::regclass::text || '_' || t.tgname, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t join pg_class c on c.oid = t.tgrelid
  where not t.tgisinternal and (c.relnamespace = 'public'::regnamespace or t.tgrelid = 'auth.users'::regclass)

  union all -- table/view privileges per role (anon, authenticated, service_role, PUBLIC)
  select '110_' || c.relname || '_' || case when x.grantee = 0 then 'PUBLIC' else x.grantee::regrole::text end,
         format('GRANT %s ON TABLE public.%I TO %s;', string_agg(x.privilege_type, ', ' order by x.privilege_type), c.relname,
                case when x.grantee = 0 then 'PUBLIC' else x.grantee::regrole::text end)
  from pg_class c, lateral aclexplode(c.relacl) x
  where c.relnamespace = 'public'::regnamespace and c.relkind in ('r', 'p', 'v')
    and (x.grantee = 0 or x.grantee::regrole::text in ('anon', 'authenticated', 'service_role'))
  group by c.relname, x.grantee

  union all -- file storage buckets
  select '120_bucket_' || b.id,
         format('-- BUCKET %s: public=%s, file_size_limit=%s, allowed_mime_types=%s', b.id, b.public,
                coalesce(b.file_size_limit::text, 'none'), coalesce(b.allowed_mime_types::text, 'any'))
  from storage.buckets b

) s;
