import { useEffect, useState } from "react";
import type { Session, User } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

type AuthSessionState = {
  initialized: boolean;
  session: Session | null;
  user: User | null;
  // Set only when a click-through from an email (magic link / invite link)
  // fails to establish a session — most commonly a flow-type mismatch
  // (the email link was generated by the server's non-PKCE admin client,
  // this browser now expects PKCE). getSession() silently discards this
  // error internally, so it's fetched separately via auth.initialize(),
  // which Supabase's own docs describe as the way to check for exactly
  // this. Null in the ordinary case (no redirect just happened).
  authRedirectError: string | null;
};

export function useAuthSession(): AuthSessionState {
  const [state, setState] = useState<AuthSessionState>({
    initialized: false,
    session: null,
    user: null,
    authRedirectError: null,
  });

  useEffect(() => {
    let active = true;

    supabase.auth.getSession().then(({ data }) => {
      if (!active) return;
      setState((prev) => ({
        ...prev,
        initialized: true,
        session: data.session,
        user: data.session?.user ?? null,
      }));
    });

    supabase.auth.initialize().then(({ error }) => {
      if (!active || !error) return;
      setState((prev) => ({ ...prev, authRedirectError: error.message }));
    });

    const { data: sub } = supabase.auth.onAuthStateChange((_event, session) => {
      if (!active) return;
      setState((prev) => ({
        ...prev,
        initialized: true,
        session,
        user: session?.user ?? null,
        // A session actually landing clears any earlier redirect error.
        authRedirectError: session ? null : prev.authRedirectError,
      }));
    });

    return () => {
      active = false;
      sub.subscription.unsubscribe();
    };
  }, []);

  return state;
}
