// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Check your environment configuration.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // Opt-in required for supabase.auth.signInWithPasskey()/registerPasskey()/
      // passkey.* — this is still a BETA API per Supabase's own docs (Sep 2026),
      // opt-in required in case its shape changes. NOTE: this file's own header
      // says "automatically generated, do not edit directly" — that's true if
      // this project ever gets re-scaffolded by whatever tool originally
      // generated it, which would silently wipe this line. Not a risk today
      // (this project is hand-edited via the GitHub web editor now, not
      // re-generated), but worth knowing if that ever changes.
      experimental: { passkey: true },
      // Added Sep 2026, verified against the installed @supabase/auth-js
      // source before changing: without this, OAuth (Google) sign-in
      // returns tokens as a URL hash fragment (#access_token=...), briefly
      // visible in the address bar and copy-pasteable — that's what led to
      // a real token exposure incident. 'pkce' returns a short-lived,
      // single-use code in the query string instead, never the actual
      // tokens. Safe here because Google sign-in is always one continuous
      // browser session (click button → redirect to Google → redirect
      // back), which is exactly what PKCE requires (it binds a verifier to
      // this client's own storage, checked on the way back).
      //
      // Deliberately NOT mirrored in client.server.ts (the admin client
      // that sends invite/magic-link emails) — PKCE cannot work there:
      // that verifier would be generated by an ephemeral server process
      // with no storage, not by the invited person's actual browser days
      // later on a different device. Forcing pkce there would silently
      // break every "click the link in your email" button. See __root.tsx
      // (buildAuthRedirectUrl callers) for how the resulting implicit/pkce
      // mismatch on that specific path is handled.
      flowType: "pkce",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
